version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: afyalink-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: healthcare
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/health.sql:/docker-entrypoint-initdb.d/afyalink.sql

volumes:
  db_data:
